### PR TITLE
Added UNPROTO VIA frame support to AGWPE TCP server

### PR DESCRIPTION
**Pull request by gherynos**
Hi @alejolp :)

I added a piece of code that handles the 'V' frame type in the AGWPE interface so that extmodem can be used with XASTIR.

Please review and let me know what you think!

### CODE REVIEW

**Comment by alejolp** [comment]
hi @Gherynos sorry for the delay, I've been away! 

This PR looks promising, but I am having trouble understanding the need for the regexp. I think we can just accept that whatever comes in that looks like a callsign, and avoid the regexp (the call and the dependency).

Also, the callsign ax25 encoding scheme can be placed elsewere, since I predict this function may be of use in the future. At least a public static or global function, somewhere in an utility cpp file.

Thanks!

Ale

**Comment by alejolp** [comment]
I still need to be convinced to include libax25 as a dependency, but it includes ax25_ntoa and ax25_aton which is what you did here.

**Comment by Gherynos** [comment]
Hi @alejolp,

no worries and thanks for your comments.

The regexp was a convenient way to check if the address contained the SSID and to extract the two components; it can be easily removed though.

Good point about the ax25 encoding procedures: I'll extract them in something like `ax25_utils` class.

Concerning libax25, I was thinking about it as well, but I didn't want to add additional dependencies, hence the redefinition of the functions.

Thanks,
Luca

**Comment by alejolp** [comment]
Great, thanks!

**Pull request merged**
